FROM docker.io/eclipse-temurin:21-jre-ubi10-minimal

ARG CREATED_DATETIME
ARG H2_VERSION

ENV H2_TCP_PORT=9092
ENV H2_CONSOLE_PORT=8082
ENV REPO_URL=https://github.com/eduardoenemark/containers/tree/main/h2

# build date/time
ENV CREATED_DATETIME=${CREATED_DATETIME}
ENV H2_VERSION=${H2_VERSION}

LABEL org.opencontainers.image.ref.name="h2-database-engine" \
    org.opencontainers.image.version="1.0" \
    org.opencontainers.image.authors="@eduardoenemark" \
    org.opencontainers.image.source="${REPO_URL}" \
    org.opencontainers.image.title="H2 Database Engine version ${H2_VERSION}" \
    org.opencontainers.image.description="H2 Database Engine container image" \
    org.opencontainers.image.created="${CREATED_DATETIME}" \
    org.opencontainers.image.licenses="GPL-3.0-only" \
    org.opencontainers.image.purpose="H2 Database image for testing and development" \
    org.opencontainers.image.vendor="t.me/eduardoenemark" \
    org.opencontainers.image.url="${REPO_URL}" \
    org.opencontainers.image.documentation="${REPO_URL}" \
    maintainer="Eduardo Vieira <eduardoenemark@gmail.com>"

COPY temp/h2/bin/h2-${H2_VERSION}.jar /h2/bin/h2-${H2_VERSION}.jar
COPY entrypoint.sh  /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

VOLUME [ "/h2/data" ]

EXPOSE ${H2_TCP_PORT}
EXPOSE ${H2_CONSOLE_PORT}

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

CMD [ "-trace", "-web", "-tcp", "-baseDir","/h2/data/" ]          
