# ---------- Base image ----------
FROM docker.io/eclipse-temurin:21-jre-ubi10-minimal

# ---------- Build arguments / environment variables ----------
ARG CREATED_DATETIME
ENV CREATED_DATETIME=${CREATED_DATETIME}

# Version of the H2 engine to use; can be overridden at build time
ARG H2_VERSION
ENV H2_VERSION=${H2_VERSION}

# ---------- Image metadata (labels) ----------
LABEL org.opencontainers.image.ref.name="h2-database-engine" \
    org.opencontainers.image.version="1.0"                  \
    org.opencontainers.image.authors="@eduardoenemark"       \
    org.opencontainers.image.source="${REPO_URL}"           \
    org.opencontainers.image.title="H2 Database Engine version ${H2_VERSION}" \
    org.opencontainers.image.description="H2 Database Engine container image" \
    org.opencontainers.image.created="${CREATED_DATETIME}"  \
    org.opencontainers.image.licenses="GPL-3.0"       \
    org.opencontainers.image.purpose="H2 Database image for testing and development" \
    org.opencontainers.image.vendor="t.me/eduardoenemark"   \
    org.opencontainers.image.url="${REPO_URL}"              \
    org.opencontainers.image.documentation="${REPO_URL}"  \
    maintainer="Eduardo Vieira <eduardoenemark@gmail.com>"

# ---------- Application code ----------
COPY temp/h2/bin/h2-${H2_VERSION}.jar /h2/bin/h2-${H2_VERSION}.jar
COPY entrypoint.sh  /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# ---------- Runtime configuration ----------
# Declare a persistent volume for database files
VOLUME [ "/h2/data" ]
EXPOSE ${H2_TCP_PORT}
EXPOSE ${H2_CONSOLE_PORT}

# ---------- Container entry point ----------
ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]
CMD [ "-trace", "-web", "-tcp", "-baseDir","/h2/data/" ]
