#https://github.com/eduardoenemark/containers/tree/main/rocm/build.sh
FROM localhost/rocm/dev-ubuntu-24.04plusplus:1.0-base-6.3.3-complete

LABEL org.opencontainers.image.ref.name=monero-rocm
LABEL org.opencontainers.image.version=1.0
LABEL org.opencontainers.image.authors=eduardoenemark
LABEL org.opencontainers.image.source=github.com/eduardoenemark/containers/monero
LABEL org.opencontainers.image.title="Monero x64-v0.18.3.4 ROCM++"

RUN apt update
RUN apt search libxcb | awk '/^libxcb-.+\//{gsub(/,now.+/,"");if($0 !~ "-dev")system("apt install -y "$1)}'
RUN apt install -y libxkbcommon-x11-0/noble
RUN apt clean

COPY ./monero-gui-v0.18.3.4/monero-wallet-gui /usr/bin
COPY ./monero-gui-v0.18.3.4/monerod /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-blockchain-stats /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-gen-ssl-cert /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-blockchain-prune-known-spent-data /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-gen-trusted-multisig /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-blockchain-depth /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-wallet-rpc /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-blockchain-usage /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-blockchain-ancestry /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-blockchain-import /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-blockchain-prune /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-wallet-cli /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-blockchain-export /usr/bin
COPY ./monero-gui-v0.18.3.4/extras/monero-blockchain-mark-spent-outputs /usr/bin
COPY ./p2pool-v4.3-linux-x64/p2pool /usr/bin
COPY ./simples/monero-node-s01.sh /usr/local/bin

#Monero ports
EXPOSE 18080/tcp
EXPOSE 18080/udp
EXPOSE 18081/tcp
EXPOSE 18081/udp
EXPOSE 18082/tcp
EXPOSE 18082/udp
EXPOSE 18083/tcp
EXPOSE 18083/udp
EXPOSE 18089/tcp
EXPOSE 18089/udp
EXPOSE 38080/tcp
EXPOSE 38080/udp
EXPOSE 38081/tcp
EXPOSE 38081/udp

#P2Pool ports
EXPOSE 37889/tcp
EXPOSE 37888/tcp
EXPOSE 3333/tcp

VOLUME [ "/monero" ]

CMD [ "/bin/bash" ]
