version: '3.8'

services:
  autossh:
    image: localhost/autossh:1.0
    container_name: autossh
    privileged: true
    network_mode: host
    restart: always
    stop_grace_period: 30s
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512m

