FROM docker.io/debian:bookworm-20240812

LABEL org.opencontainers.image.ref.name=tor-bookworm-20240812
LABEL org.opencontainers.image.version=1

RUN apt update && apt install -y apt-transport-tor && echo -e "Types: deb deb-src\nComponents: main\nSuites: bookworm\nURIs: tor+http://apow7mjfryruh65chtdydfmqfpj5btws7nbocgtaovhvezgccyjazpqd.onion/torproject.org\nArchitectures: amd64 arm64 i386\nSigned-By: /usr/share/keyrings/deb.torproject.org-keyring.gpg" > /etc/apt/sources.list.d/tor.sources

VOLUME ["/etc/tor","/var/log/tor","/var/lib/tor"]

CMD [ "/bin/bash" ]
