FROM docker.io/library/bookworm-20240812-slim

LABEL org.opencontainers.image.ref.name=tor-bookworm-20240812
LABEL org.opencontainers.image.version=1


# For the stable version.
#RUN apt update && apt install apt-transport-https

#&& apt install -y apt-transport-tor 
#&& echo "deb [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] tor+http://apow7mjfryruh65chtdydfmqfpj5btws7nbocgtaovhvezgccyjazpqd.onion/torproject.org bookworm main\ndeb [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] tor+http://apow7mjfryruh65chtdydfmqfpj5btws7nbocgtaovhvezgccyjazpqd.onion/torproject.org tor-nightly-main-bookworm main" >> /etc/apt/sources.list.d/tor.list

RUN echo "deb http://deb.debian.org/debian bookworm main" > /etc/apt/sources.list.d/debian-bookworm.list && \
    echo "deb [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] https://deb.torproject.org/torproject.org bookworm main" >> /etc/apt/sources.list.d/tor.list && \
    echo "deb-src [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] https://deb.torproject.org/torproject.org bookworm main" >> /etc/apt/sources.list.d/tor.list

# && apt update && apt install -y apt-transport-tor
VOLUME ["/etc/tor","/var/log/tor","/var/lib/tor"]

CMD [ "/bin/bash" ]
